clone_depth: 5
image:
  - Visual Studio 2022

environment:
  nodejs_version: 20.14.0
  access_token:
    secure: GEQgHcpB6CBoHNhKZisTu27ghM9+KTH0yqHbQkCyuZnPhlCGwZ0lhtu37S4dGuXs

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm@10.8.1
  - node --version
  - npm --version
  - npm install
  - npm install hexo-cli -g
  # hexo deploy工具
  - npm install hexo-deployer-git --save
  # 解决偶尔出现"Error: Cannot find module 'hexo-util'"的问题
  - npm install hexo-util --save-dev 
  - hexo --version

build_script:
  - hexo generate

on_success:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"

  - mkdir %APPVEYOR_BUILD_FOLDER%\.deploy_git
  # 从Github上拉取代码库版本，可以保留提交记录；如果直接部署相当于一个新的代码库提交，覆盖了之前的提交版本记录
  - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %APPVEYOR_BUILD_FOLDER%\.deploy_git
  - hexo deploy
